version: '3.8'

services:
  roomydomy-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    restart: unless-stopped
    container_name: roomydomy-app

  # Development service (optional)
  roomydomy-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: deps
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev
    container_name: roomydomy-dev
    profiles:
      - dev 